require "rake"
require "fileutils"

if File.exist?(File.expand_path('../../cmake_utils/Rakefile_common.rb', File.dirname(__FILE__))) then
  require_relative "../../cmake_utils/Rakefile_common.rb"
else
  require_relative "../../../Rakefile_common.rb"
end

VER = "1.0.10"

desc "install task-thread-pool"
task :install_common do
  puts "Copy task-thread-pool source".yellow
  if not Dir.exist?("task-thread-pool-#{VER}") then
    extract_zip("task-thread-pool-#{VER}.zip");
  end
  FileUtils.cp "task-thread-pool-#{VER}/include/task_thread_pool.hpp", '../../src/Utils/3rd/task_thread_pool.hpp'
end

task :install_osx   => :install_common do end
task :install_linux => :install_common do end
task :install_mingw => :install_common do end
task :install_win   => :install_common do end

task :clean       do end
task :clean_osx   do end
task :clean_linux do end
task :clean_mingw do end
task :clean_win   do end
