require 'rake/clean'

if File.exist?(File.expand_path('../cmake_utils/Rakefile_common.rb', File.dirname(__FILE__))) then
  require_relative "../cmake_utils/Rakefile_common.rb"
else
  require_relative "../../Rakefile_common.rb"
end

task :default => :install

task :install do
  case OS
  when :mac
    Rake::Task[:install_osx].invoke()
  when :linux
    Rake::Task[:install_linux].invoke()
  when :win
    Rake::Task[:install_win].invoke()
  when :mingw
    Rake::Task[:install_mingw].invoke()
  else
    raise "Unsupported platform #{OS}"
  end
end

desc "install 3rd parties for OSX"
task :install_osx do
  FileUtils.cd "Eigen"
  sh "rake install_osx"
  FileUtils.cd "../spdlog"
  sh "rake install_osx"
  FileUtils.cd "../BS_thread_pool"
  sh "rake install_osx"
  FileUtils.cd "../autodiff"
  sh "rake install_osx"
  FileUtils.cd "../task_thread_pool"
  sh "rake install_osx"
  FileUtils.cd ".."
end

desc "install 3rd parties for LINUX"
task :install_linux do
  FileUtils.cd "Eigen"
  sh "rake install_linux"
  FileUtils.cd "../spdlog"
  sh "rake install_linux"
  FileUtils.cd "../BS_thread_pool"
  sh "rake install_linux"
  FileUtils.cd "../autodiff"
  sh "rake install_linux"
  FileUtils.cd "../task_thread_pool"
  sh "rake install_linux"
  FileUtils.cd ".."
end

desc "install 3rd parties for MINGW"
task :install_mingw do
  FileUtils.cd "Eigen"
  sh "rake install_mingw"
  FileUtils.cd "../spdlog"
  sh "rake install_mingw"
  FileUtils.cd "../BS_thread_pool"
  sh "rake install_mingw"
  FileUtils.cd "../autodiff"
  sh "rake install_mingw"
  FileUtils.cd "../task_thread_pool"
  sh "rake install_mingw"
  FileUtils.cd ".."
  #FileUtils.mkdir_p "../lib3rd/include"
  #FileUtils.mkdir_p "../lib3rd/lib"
  #FileUtils.mkdir_p "../lib3rd/dll"
end

desc "install 3rd parties for WINDOWS"
task :install_win do
  FileUtils.cd "Eigen"
  sh "rake install_win"
  FileUtils.cd "../spdlog"
  sh "rake install_win"
  FileUtils.cd "../BS_thread_pool"
  sh "rake install_win"
  FileUtils.cd "../autodiff"
  sh "rake install_win"
  FileUtils.cd "../task_thread_pool"
  sh "rake install_win"
  FileUtils.cd ".."
  FileUtils.mkdir_p "../lib3rd/include"
  FileUtils.mkdir_p "../lib3rd/lib"
  FileUtils.mkdir_p "../lib3rd/dll"
end

desc "clean 3rd parties for OSX"
task :clean_osx do
  FileUtils.cd "Eigen"
  sh "rake clean_osx"
  FileUtils.cd ".."
end

desc "clean 3rd parties for LINUX"
task :clean_linux do
  FileUtils.cd "Eigen"
  sh "rake clean_linux"
  FileUtils.cd ".."
end

desc "clean 3rd parties for MINGW"
task :clean_mingw do
  FileUtils.cd "Eigen"
  sh "rake clean_mingw"
  FileUtils.cd ".."
end

desc "clean 3rd parties for WINDOWS"
task :clean_win do
  FileUtils.cd "Eigen"
  sh "rake clean_win"
  FileUtils.cd ".."
end
