require "rake"
require "fileutils"

if File.exist?(File.expand_path('../../cmake_utils/Rakefile_common.rb', File.dirname(__FILE__))) then
  require_relative "../../cmake_utils/Rakefile_common.rb"
else
  require_relative "../../../Rakefile_common.rb"
end

VER = "5.0.0"

desc "install FMT"
task :install_common do
  puts "Copy BS source".yellow
  if not Dir.exist?("thread-pool-#{VER}") then
    extract_zip("thread-pool-#{VER}.zip");
  end
  FileUtils.cp "thread-pool-#{VER}/include/BS_thread_pool.hpp", '../../src/Utils/3rd/BS_thread_pool.hpp'
end

task :install_osx   => :install_common do end
task :install_linux => :install_common do end
task :install_mingw => :install_common do end
task :install_win   => :install_common do end

task :clean       do end
task :clean_osx   do end
task :clean_linux do end
task :clean_mingw do end
task :clean_win   do end
