require 'rake/clean'
require "fileutils"

if File.exist?(File.expand_path('../../cmake_utils/Rakefile_common.rb', File.dirname(__FILE__))) then
  require_relative "../../cmake_utils/Rakefile_common.rb"
else
  require_relative "../../../Rakefile_common.rb"
end

CLEAN.clear_exclude.exclude { |fn| fn.pathmap("%f").downcase == "core" }

VER = "5.0.0"

desc "install Eigen3"
task :install_common do
  puts "Copy Eigen3 source".yellow
  if File.exist?("eigen-#{VER}.zip") then
  else
    url_download( "https://gitlab.com/libeigen/eigen/-/archive/#{VER}/eigen-#{VER}.zip", "eigen-#{VER}.zip" )
  end
  if Dir.exist?("eigen-#{VER}/Eigen") then
  else
    extract_zip("eigen-#{VER}.zip");
  end
  FileUtils.mkdir_p('../../src/Utils/3rd')
  FileUtils.cp_r "eigen-#{VER}/Eigen/.", '../../src/Utils/3rd/Eigen', remove_destination: true
end

task :install       => :install_common do end
task :install_osx   => :install_common do end
task :install_linux => :install_common do end
task :install_mingw => :install_common do end
task :install_win   => :install_common do end

task :clean       do end
task :clean_osx   do end
task :clean_linux do end
task :clean_mingw do end
task :clean_win   do end

